<?php
$girls = [
    [
        'id' => '1',
        'name' => 'あい',
        'age' => '26',
        'img' => '1',
        'time' => '10:30〜15:00',
        'tall' => '159',
        'bust' => '85(C)',
        'waist' => '60',
        'height' => '82',
        'reserve' => '2000',
        'newface' => false,
        'sun' => true,
        'mon' => true,
        'tue' => false,
        'wed' => false,
        'thu' => true,
        'fri' => true,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => '清楚系',
        'tag2' => 'エロエロ',
        'diary' => true,
        'diary-img' => 'ai',
        'diary-text' => '退勤しました✨<br>
会いに来てくれたお兄様ありがとうございました❣️<br>
今日はあんまりよくないお天気でしたがお気に入りの<br>
ハンバーグを食べたら元気になりました✨',
        'diary2' => true,
        'diary2-img' => 'secret',
        'diary2-text' => 'あいだよ> < ♡<br>
えっちぃ写真あげたよ🌟<br>
会員登録よろしくね❤️',
        'diary3' => true,
        'diary3-img' => 'ai_1',
        'diary3-text' => '退勤しました✨<br>
会いに来てくれたお兄様ありがとうございました❣️<br>
差し入れめっちゃ美味しかったです✨',
    ],
    [
        'id' => '2',
        'name' => 'めいさ',
        'age' => '21',
        'img' => 'none',
        'time' => '09:30〜13:00',
        'tall' => '160',
        'bust' => '82(C)',
        'waist' => '60',
        'height' => '80',
        'reserve' => '3000',
        'newface' => true,
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => true,
        'fri' => true,
        'sat' => false,
        'date' => '',
        'tag1' => '色白美肌',
        'tag2' => '清楚系',
        'description' => '誰もが認める最高峰の清楚系美少女！<br>
        普通の美しさを軽々と飛び越えた華麗なる
        容姿にノックアウト！！礼儀正しさや<br>
        丁寧な言葉遣い、愛嬌溢れる人懐っこい笑顔と純真無垢!幸せな気分になってしまいます！<br>',
    ],
    [
        'id' => '3',
        'name' => 'ゆうり',
        'age' => '21',
        'img' => '2',
        'time' => '08:00〜10:00',
        'tall' => '155',
        'bust' => '84(C)',
        'waist' => '60',
        'height' => '82',
        'reserve' => '3000',
        'newface' => false,
        'sun' => true,
        'mon' => false,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => true,
        'sat' => false,
        'date' => '',
        'tag1' => '潮吹き',
        'tag2' => 'ドMちゃん', 
        'diary' => true,
        'diary-img' => 'secret',
        'diary-text' => '久々の限定写メ覗いてみてね⭐️',
        'diary2' => true,
        'diary2-img' => 'yuuri',
        'diary2-text' => '北海道行ってました✨<br>
美味しいものいっぱい食べたから元気いっぱい❣️<br>
今日は本指名様でご予約満了です☀️',
    ],
    [
        'id' => '4',
        'name' => '復活の【きい】',
        'age' => '21',
        'img' => '3',
        'time' => '12:00〜16:00',
        'tall' => '165',
        'bust' => '83(C)',
        'waist' => '60',
        'height' => '82',
        'reserve' => '5000',
        'newface' => false,
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => true,
        'sat' => false,
        'date' => '',
        'tag1' => 'キャバ系',
        'tag2' => 'ご奉仕タイプ',
        'diary' => true,
        'diary-img' => 'secret',
        'diary-text' => 'きいです❤️<br>
1週間ぶりの出勤ー！<br>
お誘い待ってます^_^',
    ],
    [
        'id' => '5',
        'name' => 'あかり',
        'age' => '25',
        'img' => 'none',
        'time' => '12:00〜16:00',
        'tall' => '152',
        'bust' => '85(C)',
        'waist' => '60',
        'height' => '85',
        'reserve' => '2000',
        'newface' => true,
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => false,
        'date' => '',
        'tag1' => 'ドM美尻',
        'tag2' => 'スタイル抜群',
        'description' => '【業界未経験】可愛すぎるルックスと、細身の美ボディー！<br>
        業界で働いて無さそうな素人要素も持ち合わせ、今後の人気が出ること間違いなし!まさしくハイレベルなのでお早目にお遊びを推奨いたします！<br>
なのでお早目にお遊びを推奨いたします！<br>
',
        'diary' => true,
        'diary-img' => 'secret',
        'diary-text' => 'あかりだよ⭐️<br>
今日は大好きな本指名様の<br>
ご予約で埋まってしまいました❤️<br>
感謝しかないです🎵
',
    ],
    [
        'id' => '6',
        'name' => 'なつき',
        'age' => '22',
        'img' => '4',
        'time' => '14:00〜20:00',
        'tall' => '168',
        'bust' => '82(C)',
        'waist' => '62',
        'height' => '86',
        'reserve' => '3000',
        'newface' => false,
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => true,
        'sat' => false,
        'date' => '',
        'tag1' => '清楚系',
        'tag2' => 'エロエロ',
        'diary' => true,
        'diary-img' => 'natsuki',
        'diary-text' => '大好きなバスクチーズケーキ⭐️<br>
本日もよろしくお願いいたします❤️',
    ],
    [
        'id' => '7',
        'name' => 'ゆあ',
        'age' => '22',
        'img' => '5',
        'time' => '14:00〜20:00',
        'tall' => '158',
        'bust' => '88(E)',
        'waist' => '60',
        'height' => '86',
        'reserve' => '3000',
        'newface' => false,
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => false,
        'date' => '',
        'tag1' => 'モデル級',
        'tag2' => '美乳',
    ],
    [
        'id' => '8',
        'name' => 'さき',
        'age' => '25',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '162',
        'bust' => '86(E)',
        'waist' => '60',
        'height' => '84',
        'reserve' => '3000',
        'newface' => true,
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => false,
        'sat' => true,
        'date' => '2024/11/27',
        'tag1' => '美乳・美尻',
        'tag2' => '甘えん坊',
        'description' => 'プレミアムガール！！！<br>
某有名大学ミスコンファイナリスト☆<br>
整った顔立ちに 美しすぎるスタイルは一度見た者の心を決して離さないこと間違いなしの逸材です！<br>  
',
        'diary' => true,
        'diary-img' => 'saki',
        'diary-text' => 'ラスト枠空いてます❤️<br>
ラブラブしよ⭐️',
    ],
    [
        'id' => '9',
        'name' => 'みつき',
        'age' => '27',
        'img' => '6',
        'time' => '14:00〜20:00',
        'tall' => '160',
        'bust' => '88(F)',
        'waist' => '62',
        'height' => '86',
        'reserve' => '2000',
        'newface' => false,
        'sun' => false,
        'mon' => false,
        'tue' => true,
        'wed' => true,
        'thu' => false,
        'fri' => false,
        'sat' => true,
        'date' => '',
        'tag1' => 'スタイル抜群',
        'tag2' => 'ドM美尻',
        'diary' => true,
        'diary-img' => 'mitsuki',
        'diary-text' => '出勤したよ〜っ！<br>
今日もご予約お待ちしてます(〃ω〃)♡',
    ],
    [
        'id' => '10',
        'name' => 'しおん',
        'age' => '22',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => 'T164',
        'bust' => '86(F)',
        'waist' => '62',
        'height' => '88',
        'reserve' => '3000',
        'newface' => true,
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => false,
        'sat' => false,
        'date' => '2024.10.28',
        'tag1' => '甘えん坊',
        'tag2' => '美乳',
        'description' => 'とっても甘えん坊な<br>    
【しおんちゃん】の入店でございます！<br>
まさに純白という文字が似合うような<br>
甘えん坊さんです！<br>
    清楚感と透明感のあるオーラで底抜けに<br>
明るい愛嬌でお客様のハートをロックオン<br>
是非可愛いしおんちゃんを体感ください<br>
',
        'diary' => true,
        'diary-img' => 'sion',
        'diary-text' => 'こんにちは！しおんです> < ♡<br>
お兄さんたちと沢山お話したいなあ💭<br>
本日もお誘いお待ちしてます🎀',
    ],
    [
        'id' => '11',
        'name' => 'ななせ',
        'age' => '28',
        'img' => '7',
        'time' => '14:00〜20:00',
        'tall' => '158',
        'bust' => '85(C)',
        'waist' => '60',
        'height' => '82',
        'reserve' => '3000',
        'newface' => false,
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => false,
        'sat' => false,
        'date' => '',
        'tag1' => 'ロリータ',
        'tag2' => '色白美肌',
        'diary' => true,
        'diary-img' => 'nanase',
        'diary-text' => 'なお仕事前のご褒美⭐️',
        'diary2' => true,
        'diary2-img' => 'nanase_2',
        'diary2-text' => '今日は遅めの出勤、12:00から！<br>
お兄様たちが来てくれるの楽しみに待ってます😊',
    ],
    [
        'id' => '12',
        'name' => 'エリサ',
        'age' => '21',
        'img' => '8',
        'time' => '14:00〜20:00',
        'tall' => '152',
        'bust' => '82(B)',
        'waist' => '58',
        'height' => '80',
        'reserve' => '5000',
        'newface' => false,
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => false,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => 'キャバ系',
        'tag2' => 'ご奉仕タイプ',
    ],
    [
        'id' => '13',
        'name' => 'めぐ',
        'age' => '22',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '155',
        'bust' => '85(C)',
        'waist' => '60',
        'height' => '82',
        'reserve' => '3000',
        'newface' => true,
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => true,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => '感度最高',
        'tag2' => '潮吹き',
        'description' => 'プレミアムガール！！！<br>
        某有名大学ミスコンファイナリスト ☆
        整った顔立ちに 美しすぎるスタイルは 一度見た者の心を決して離さないこと間違いなしの逸材です！
',
    ],
    [
        'id' => '14',
        'name' => 'まき',
        'age' => '20',
        'img' => '9',
        'time' => '14:00〜20:00',
        'tall' => '160',
        'bust' => '83(C)',
        'waist' => '60',
        'height' => '80',
        'reserve' => '3000',
        'newface' => false,
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => true,
        'sat' => false,
        'date' => '',
        'tag1' => '甘えん坊',
        'tag2' => '美尻',
    ],
    [
        'id' => '15',
        'name' => 'しらゆき',
        'age' => '25',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '160',
        'bust' => '84(E)',
        'waist' => '60',
        'height' => '84',
        'reserve' => '3000',
        'newface' => true,
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => true,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => 'モデル級',
        'tag2' => '感度最高',
        'description' => 'ただ一言...めちゃくちゃ可愛いです<br>
こんな女の子と遊べるのはただただ<br>
羨ましい限りです！<br>
まさに正真正銘の美少女<br>
完全業界未経験の女の子になりますので<br>
優しく紳士的なお客様限定になります。<br>
',
    ],
    [
        'id' => '16',
        'name' => 'まい',
        'age' => '20',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '162',
        'bust' => '86(E)',
        'waist' => '60',
        'height' => '84',
        'reserve' => '3000',
        'newface' => false,
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => true,
        'sat' => false,
        'date' => '',
        'tag1' => '感度最高',
        'tag2' => '美乳・美尻',
        'description' => 'まい（20歳）',
    ],
    [
        'id' => '17',
        'name' => 'れいさ',
        'age' => '22',
        'img' => '10',
        'time' => '14:00〜20:00',
        'tall' => '158',
        'bust' => '81(B)',
        'waist' => '58',
        'height' => '80',
        'reserve' => '2000',
        'newface' => false,
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => true,
        'thu' => true,
        'fri' => false,
        'sat' => true,
        'date' => '2024/11/27',
        'tag1' => '美脚',
        'tag2' => '言葉責め',
        'diary' => true,
        'diary-img' => 'reisa',
        'diary-text' => 'おはようございます🌞<br>
花粉症で鼻水ずるずるのなつはです🤧🤧<br>
ほんまにこの時期の花粉症辛すぎ🌀<br>
今日も20時まで受付してます❤︎<br>
お時間合えばぜひっ！🕊️',
    ],
    [
        'id' => '18',
        'name' => 'ふうか',
        'age' => '25',
        'img' => '11',
        'time' => '14:00〜20:00',
        'tall' => '160',
        'bust' => '85(D)',
        'waist' => '60',
        'height' => '84',
        'reserve' => '4000',
        'newface' => false,
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => true,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => 'テクニシャン',
        'tag2' => 'バキューム',
    ],
    [
        'id' => '19',
        'name' => 'ゆか',
        'age' => '22',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '158',
        'bust' => '88(E)',
        'waist' => '60',
        'height' => '86',
        'reserve' => '3000',
        'newface' => false,
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => true,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => '巨乳・美乳',
        'tag2' => '美尻',
    ],
    [
        'id' => '20',
        'name' => 'みい',
        'age' => '20',
        'img' => '12',
        'time' => '14:00〜20:00',
        'tall' => '160',
        'bust' => '82(C)',
        'waist' => '60',
        'height' => '80',
        'reserve' => '2000',
        'newface' => true,
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => false,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => '色白美肌',
        'tag2' => 'モデル級',
        'description' => '黒髪・色白！！清楚で上品！！<br>
綺麗なお顔立ちにスラっと伸びた長い脚！！<br>
ハイスペック美人♡<br>
是非ともご予約お待ちしております♡<br>
',
    ],
    [
        'id' => '21',
        'name' => 'えりか',
        'age' => '25',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '165',
        'bust' => '88(G)',
        'waist' => '62',
        'height' => '88',
        'reserve' => '2000',
        'newface' => true,
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => true,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => 'バキューム',
        'tag2' => 'テクニシャン',
        'description' => '業界未経験で色白でお綺麗な言葉がぴったり！綺麗で大人な雰囲気が魅力で喋ってみると優しく丁寧な感じが更に魅力度UP！こんな嬌艶で品性がある女性とイチャイチャしたいですね♡♡
',
        'diary' => true,
        'diary-img' => 'secret',
        'diary-text' => '個人オプション<br>
今日は童貞殺しのニット⭐️',
    ],
    [
        'id' => '22',
        'name' => 'のん',
        'age' => '23',
        'img' => '13',
        'time' => '14:00〜20:00',
        'tall' => '160',
        'bust' => '85(D)',
        'waist' => '58',
        'height' => '80',
        'reserve' => '5000',
        'newface' => false,
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => false,
        'sat' => true,
        'date' => '2024/11/27',
        'tag1' => 'セレブ系',
        'tag2' => 'モデル級',
        'diary' => true,
        'diary-img' => 'non',
        'diary-date' => '2024年11 月11日 22 :58',
        'diary-text' => '大好きなTさん❤️<br>
今日も可愛いって言ってくれてありがとう^_^<br>
野球の話めっちゃ楽しかったです🌟',
    ],
    [
        'id' => '23',
        'name' => 'まいか',
        'age' => '21',
        'img' => '14',
        'time' => '14:00〜20:00',
        'tall' => '165',
        'bust' => '83(C)',
        'waist' => '60',
        'height' => '85',
        'reserve' => '3000',
        'newface' => false,
        'sun' => true,
        'mon' => false,
        'tue' => true,
        'wed' => false,
        'thu' => true,
        'fri' => true,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => '清潔感100点',
        'tag2' => '激カワ美人',
        'diary' => true,
        'diary-img' => 'maika',
        'diary-text' => 'まいかだよ> < ♡<br>
えっちなこと妄想しちゃって...💭<br>
早く逢いに来て❤️',
        'diary2' => true,
        'diary2-img' => 'maika_1',
        'diary2-text' => '出勤しました✨️<br>
よろしくです🎀',
        'diary3' => true,
        'diary3-img' => 'maika_2',
        'diary3-text' => 'おはようございます☀️まいかです♪<br>
昨日来てくれた2人のお兄様ありがとう~☆<br>
いっぱい笑った日でした❤︎',    
    ],
    [
        'id' => '24',
        'name' => 'きこ',
        'age' => '25',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '160',
        'bust' => '82(C)',
        'waist' => '60',
        'height' => '82',
        'reserve' => '3000',
        'newface' => true,
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => false,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => '清楚系',
        'tag2' => 'エロエロ',
        'description' => 'SS級の極上スレンダー美女電撃入店！<br>
瞬く間に全てを魅了し尽くキレカワ系FACE
スレンダーな身体は、お手入れが行き届いた
キメ細かい白い美肌に形・色・まさに美乳
そして輝く流線美が眩しいクビレ...
研ぎ澄まされたボディラインは
最高のスペックです！！
',
        'diary' => true,
        'diary-img' => 'secret',
        'diary-text' => 'ききこだよ❤︎<br>
自慢のお尻公開❤️<br>
ラスト枠逢いておりまする✨',
    ],
    [
        'id' => '25',
        'name' => 'ゆい',
        'age' => '20',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '162',
        'bust' => '88(F)',
        'waist' => '62',
        'height' => '86',
        'reserve' => '3000',
        'newface' => false,
        'sun' => true,
        'mon' => false,
        'tue' => true,
        'wed' => false,
        'thu' => true,
        'fri' => true,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => '敏感',
        'tag2' => '美巨乳',
        'diary' => true,
        'diary-img' => 'yui',
        'diary-text' => '大好きな本指名様❤️<br>
ほんまにチョコクロ買ってきてくれた🎵<br>
感謝しかない❤️ゆいは、いつも甘やかされてますw',
        'diary2' => true,
        'diary2-img' => 'yui_1',
        'diary2-text' => 'スーツの似合おうMなお兄さん❤️<br>
大好きなロールケーキありがとう🎵<br>
何よりゆいにに会いに来てくれて本当にありがとう❤️',
        'diary3' => true,
        'diary3-img' => 'yui_2',
        'diary3-text' => '誰か早くいたずらして🌟<br>    
我慢できないんです❤️',      
    ],
    [
        'id' => '26',
        'name' => 'あおい',
        'age' => '20',
        'img' => '15',
        'time' => '14:00〜20:00',
        'tall' => '155',
        'bust' => '86(E)',
        'waist' => '60',
        'height' => '82',
        'reserve' => '5000',
        'newface' => false,
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => false,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => '店長おすすめ',
        'tag2' => 'モデル顔負け',
        'diary' => true,
        'diary-img' => 'aoi',
        'diary-text' => '今日は23時から出勤してます❤︎<br>
寂しいから早く逢いにきてね⭐️',
        'diary2' => true,
        'diary2-img' => 'secret',
        'diary2-text' => 'いつもより早めに帰っちゃうから<br>
早めに会いに来て欲しい💞👍🏻',  
    ],
    [
        'id' => '27',
        'name' => 'えりな',
        'age' => '25',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '165',
        'bust' => '84(D)',
        'waist' => '60',
        'height' => '82',
        'reserve' => '5000',
        'newface' => true,
        'sun' => true,
        'mon' => false,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => true,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => '超エロい',
        'tag2' => '超敏感',
        'description' => '完全業界未経験♡<br>
純白清楚ロリカワ少女♡<br>
とっても可愛いい女の子「えりな」ちゃんです♡<br>
とっても癒しをもらえます♡<br>
是非とも癒されに来てください！<br>
',
        'diary' => true,
        'diary-img' => 'erina',
        'diary-text' => '遅めの出勤です！<br>
来てくれるの楽しみに待ってます😊',    
    ],
    [
        'id' => '28',
        'name' => 'あきら',
        'age' => '20',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '170',
        'bust' => '84(C)',
        'waist' => '60',
        'height' => '82',
        'reserve' => '3000',
        'newface' => true,
        'sun' => false,
        'mon' => true,
        'tue' => true,
        'wed' => false,
        'thu' => false,
        'fri' => false,
        'sat' => true,
        'date' => '2024/11/27',
        'tag1' => '甘えん坊',
        'tag2' => '美乳・美尻',
        'description' => '超絶カワユイ女の子♡<br>
「あきら」ちゃんです！！<br>
スレンダーのモデル体型♡<br>    
すらっと伸びた美脚♡<br>
是非ともご予約お待ちしております♡<br>
',  
        'diary' => true,
        'diary-img' => 'akira',
        'diary-text' => '退勤しました✨<br>
一人焼肉❣️この時間が一番の癒しハラミサイコー✨',
    ],
    [
        'id' => '29',
        'name' => 'しおり',
        'age' => '25',
        'img' => '16',
        'time' => '14:00〜20:00',
        'tall' => '152',
        'bust' => '86(F)',
        'waist' => '60',
        'height' => '85',
        'reserve' => '3000',
        'newface' => false,
        'sun' => true,
        'mon' => false,
        'tue' => false,
        'wed' => true,
        'thu' => false,
        'fri' => true,
        'sat' => false,
        'date' => '2024/11/27',
        'tag1' => 'ご奉仕タイプ',
        'tag2' => '巨乳',
        'diary' => true,
        'diary-img' => 'secret',
        'diary-text' => 'しおりだよ❤️<br>
しおりとエッチなことしてくださるお兄様方<br>
    ぜひ遊びに来てください❤️<br>',
        'diary2' => true,
        'diary2-img' => 'siori',
        'diary2-text' => 'しおりです😊<br>
いっぱいいっぱいいちゃいちゃしようね❤️',
    ],
    [
        'id' => '30',
        'name' => 'せいら',
        'age' => '25',
        'img' => 'none',
        'time' => '14:00〜20:00',
        'tall' => '165',
        'bust' => '88(G)',
        'waist' => '62',
        'height' => '88',
        'reserve' => '2000',
        'newface' => true,
        'sun' => false,
        'mon' => true,
        'tue' => false,
        'wed' => true,
        'thu' => true,
        'fri' => false,
        'sat' => true,
        'date' => '2024/11/27',
        'tag1' => 'バキューム',
        'tag2' => 'テクニシャン',
        'description' => '人を癒す才能に溢れている<br>  
「せいら」ちゃんルックス、愛嬌、笑顔、一生懸命さどれを取っても素晴らしすぎます。「せいら」ちゃんと過ごす甘美な時間<br>
きっとお客様の良い思い出になる事でしょう。<br>
',
        'diary' => true,
        'diary-img' => 'secret',
        'diary-text' => '半年ぶりに会いに来てくれた本指名様♡<br>
久しぶりに会えてほんっとに嬉しかった〜！',
    ],   
];



?>